analyzer:
  strong-mode:
    implicit-casts: false
  errors:
    todo: ignore
  exclude:
    - flutter/**
    - lib/api/*.dart

include: package:lints/recommended.yaml
linter:
  rules:
    constant_identifier_names: false
